framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        failure_transport: failed
        transports:
            collect_user_info:
                serializer: messenger.transport.symfony_serializer
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: collect_user_info
                retry_strategy:
                    max_retries: 5
            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    queue_name: failed

        routing:
            'App\Message\UserInfoMessage': collect_user_info